# Generated by Django 4.1.7 on 2023-07-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene1Choice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('consequence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scene1Choice2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('consequence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scene1Choice3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('consequence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scene2Choice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('consequence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scene2Choice2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('consequence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scene2Choice3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('consequence', models.CharField(max_length=100)),
            ],
        ),
    ]
