# Generated by Django 4.1.7 on 2023-07-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene1choice1',
            name='consequence',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scene1choice1',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scene1choice2',
            name='consequence',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scene1choice2',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scene1choice3',
            name='consequence',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scene1choice3',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scene2choice1',
            name='consequence',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scene2choice1',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scene2choice2',
            name='consequence',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scene2choice2',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scene2choice3',
            name='consequence',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scene2choice3',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
