# Generated by Django 4.1.7 on 2023-07-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_scene1choice1_consequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene3Choice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('consequence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scene3Choice2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('consequence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scene3Choice3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('consequence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scene4Choice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('consequence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scene4Choice2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('consequence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scene4Choice3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('consequence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scene5Choice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('consequence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scene5Choice2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('consequence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scene5Choice3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('consequence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='scene2choice3',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
