# Generated by Django 4.1.7 on 2023-07-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_scene3choice1_scene3choice2_scene3choice3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro13', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Intro2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IntroStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
