# Generated by Django 4.1.7 on 2023-07-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_intro1_intro2_introstep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introstep',
            old_name='text',
            new_name='introStep',
        ),
    ]
